### ISSUE TITLE
Drop repo's 'crystallang' topic

### ISSUE THREAD

**Issue by matiasgarciaisaia** [samueleaton/sentry#11]
The Crystal community has somewhat decided to [use `crystal` as the language's topic](https://github.com/search?utf8=✓&q=topic%3Acrystal&type=Repositories).

To avoid fragmentation in the community, please drop the `crystallang` topic, that only has ~12 repositories at the moment. We're sticking to `crystal`, instead.

Any contributor can change it from the repo's homepage.

See crystal-lang/crystal#4241 for more context.

Thank you very much :)

**Comment by samueleaton** [comment]
done
