### ISSUE TITLE
Create a release tag

### ISSUE THREAD

**Issue by faustinoaq** [samueleaton/sentry#16]
Hi @samueleaton Sentry is being used in several crystal projects. Would be good to release a stable tag line `v0.1.1` to avoid using master (possible unexpected changes)

Thanks you for this useful shard! 😄

**Comment by samueleaton** [comment]
I just pushed a fresh set of tags (`v0.1.0`)

I'm also going to set up some CI and some other things to enforce a better production-grade deployment.

**Comment by faustinoaq** [comment]
@samueleaton Thanks you so much! :)
