### ISSUE TITLE
Publish tag 0.1.0 again

### ISSUE THREAD

**Issue by faustinoaq** [samueleaton/sentry#19]
Hi @samueleaton !

The tag `v0.1.0` is the latest, however the `shard.yml` file had an incorrect version `v1.0.0`, (already fixed on https://github.com/samueleaton/sentry/commit/3475f6f20f2e73b6d420616cc3a8d32034745fb9)

So, currently exists a dependency mismatch.

![screenshot_20171108_054201](https://user-images.githubusercontent.com/3067335/32544779-8c1bd4ac-c447-11e7-9aad-3ca7d6618167.png)

Can you push the tag `v0.1.0` again ?

**Comment by faustinoaq** [comment]
![screenshot_20171109_121022](https://user-images.githubusercontent.com/3067335/32618877-f6bb89ec-c546-11e7-8601-2581b905488c.png)

@samueleaton Just waiting for sentry to be _Up to date_ 😄

**Comment by samueleaton** [comment]
sorry. bumped version in shard.yml *before* changing the git tag this time. New tag should be `v0.1.1`. Is it fixed?

**Comment by faustinoaq** [comment]
It is, Thanks you!
