### ISSUE TITLE
Enable configuration through a `.sentry-config` file or similar

### ISSUE THREAD

**Issue by faultyserver** [samueleaton/sentry#20]
I've found myself using `sentry` on a number of my projects, enough so that I actually installed it to `/usr/local/bin` so I don't have to add the binary to each one.

One thing that I've found, though, is that a lot of my projects have some extra files I'd like to watch (e.g., Slang templates), or some that I'd like to ignore, or need a custom build/run command. All of this is possible to do on the command line, but it's tedious to have to type out the command with all of those options every time I start working on a project.

A solution I'd like to see for that would be the ability to load the configuration options from a file like `.sentry` or `.sentry-config` (ideally the file name could also be specified in the CLI). I figure a simple YAML file would suffice.

I'd be happy to spike on this and make a PR if you'd like.

**Comment by samueleaton** [comment]
Hey, Jon! I think this is a good idea.

A default `.sentry.yml` in the current directory would be good, with the option to pass `-c, --config` as an explicit path to a file of any name.

I'd love to see how you would implement it.

**Comment by samueleaton** [comment]
Not to insult your intelligence, but In the interim might I suggest just putting the command to start sentry in a project specific shell script and just run that 😊

**Comment by faultyserver** [comment]
No worries :) For most of them I've up ended making Makefile rules for now.

I should have some time tomorrow to get a basic idea in place.

**Comment by faultyserver** [comment]
This issue can be closed since #21 was merged :)
