### ISSUE TITLE
Sentry installation crashes on Debian

### ISSUE THREAD

**Issue by mxwsxr** [samueleaton/sentry#26]
Hello,

I'm trying to install SENTRY on Debian for my Crystal+Kemal project but when I'm executing the given command:

`curl -fsSLo- https://raw.githubusercontent.com/samueleaton/sentry/master/install.cr | crystal eval`

it gives me an confusing error as in given here:

🤖  Fetching sentry files... success
🤖  Compiling sentry using --release flag...
/usr/bin/ld: cannot find -lyaml
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/albert/repos/eins_app/sentry'  -rdynamic  -lyaml -lpcre -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
🤖  Bzzt. There was an error compiling sentry.

Is there any way to fix this? The shown error seems very confusing to me and I don't know how to resolve this.

Thank you!

**Comment by samueleaton** [comment]
Sorry. I've been away on vacation. what happens when you try to use the ruby install script?

```
curl -fsSLo- https://raw.githubusercontent.com/samueleaton/sentry/master/install.rb | ruby
```

**Comment by samueleaton** [comment]
Also, what version of crystal are you using?

**Comment by mxwsxr** [comment]
Hi Samuel, at that moment I was using the 0.24 version of Crystal. The ruby install script didn't work.

**Comment by samueleaton** [comment]
I just installed crystal in a docker container running Debian (Jessie) and I had to install a few dependencies:

```
apt-get install -y curl build-essential apt-transport-https libyaml-dev
```

A google search of your error showed this same issue in other crystal projects, like https://github.com/amberframework/granite/issues/178

**Comment by mxwsxr** [comment]
I did this, it installed the dependencies. Now I got this:

```
🤖  Fetching sentry files... success
🤖  Compiling sentry using --release flag...
Error in dev/sentry_cli.cr:87: instantiating 'Sentry::ProcessRunner#run()'

  process_runner.run
                 ^~~

in dev/sentry.cr:233: instantiating 'loop()'

      loop do
      ^~~~

in dev/sentry.cr:233: instantiating 'loop()'

      loop do
      ^~~~

in dev/sentry.cr:238: instantiating 'scan_files()'

        scan_files
        ^~~~~~~~~~

in dev/sentry.cr:214: instantiating 'Dir:Class#glob(Array(String))'

      Dir.glob(files) do |file|
          ^~~~

in /usr/share/crystal/src/dir/glob.cr:32: instantiating 'Array(String)#each()'

    patterns.each do |ptrn|
             ^~~~

in /usr/share/crystal/src/indexable.cr:148: instantiating 'each_index()'

    each_index do |i|
    ^~~~~~~~~~

in /usr/share/crystal/src/indexable.cr:148: instantiating 'each_index()'

    each_index do |i|
    ^~~~~~~~~~

in /usr/share/crystal/src/dir/glob.cr:32: instantiating 'Array(String)#each()'

    patterns.each do |ptrn|
             ^~~~

in /usr/share/crystal/src/dir/glob.cr:98: instantiating 'scandir(String, String, Regex, Int32, Int32, Bool)'

      scandir(dir, nested_path, regex, 0, recursion_depth, wants_dir) do |path|
      ^~~~~~~

in /usr/share/crystal/src/dir/glob.cr:98: instantiating 'scandir(String, String, Regex, Int32, Int32, Bool)'

      scandir(dir, nested_path, regex, 0, recursion_depth, wants_dir) do |path|
      ^~~~~~~

in dev/sentry.cr:214: instantiating 'Dir:Class#glob(Array(String))'

      Dir.glob(files) do |file|
          ^~~~

in dev/sentry.cr:215: instantiating 'get_timestamp(String)'

        timestamp = get_timestamp(file)
                    ^~~~~~~~~~~~~

in dev/sentry.cr:191: undefined method 'info' for File:Class

      File.info(file).modification_time.epoch.to_s
           ^~~~


🤖  Bzzt. There was an error compiling sentry.
```

**Comment by samueleaton** [comment]
now thats because Sentry was recently update to be compatible with the latest Crystal v0.25.0

I forgot to add instructions to the README for v0.24.x. I just did it but here it is for reference. Sorry about that.

`curl -fsSLo- https://raw.githubusercontent.com/samueleaton/sentry/crystal-v0.24.2/install.cr | crystal eval`
