### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by kolyaio** [samueleaton/sentry#34]
.Hey! 

I'm trying to install sentry but during the installation it prints out the following error. 

It's seems like some compiling error. 

I'm using crystal 0.26.0  on macOS 10.13.6
```
🤖  Fetching sentry files... success
🤖  Compiling sentry using --release flag...
Assertion failed: (cast<DISubprogram>(Scope)->describes(MF->getFunction())), function getOrCreateRegularScope, file /var/cache/omnibus/src/llvm/llvm-3.9.1.src/lib/CodeGen/LexicalScopes.cpp, line 159.
🤖  Bzzt. There was an error compiling sentry.
```

I'm runnig the following command : 
```
curl -fsSLo- https://raw.githubusercontent.com/samueleaton/sentry/master/install.cr | crystal eval
```

tried using the troubleshoot method without the ruby script and yet it doesn't works. 

```
crystal build --release dev/sentry_cli.cr -o ./sentry
Assertion failed: (cast<DISubprogram>(Scope)->describes(MF->getFunction())), function getOrCreateRegularScope, file /var/cache/omnibus/src/llvm/llvm-3.9.1.src/lib/CodeGen/LexicalScopes.cpp, line 159.
/Users/nikolai/.crenv/versions/0.26.1/bin/crystal: line 102: 59181 Abort trap: 6           "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

**Comment by samueleaton** [comment]
this looks like its a bigger issue than Sentry. your error just mentions an internal error with LLVM and it doesn't say anything specifically about the Crystal program.

looks similar to this: https://github.com/crystal-lang/crystal/issues/5497

**Comment by samueleaton** [comment]
it looks like you are using LLVM 3.9. You may need to update your version of LLVM to 4.0 or 5.0.
