### ISSUE TITLE
Crystal 0.35.1 deprecated

### ISSUE THREAD

**Issue by onliniak** [samueleaton/sentry#56]
`🤖  Fetching sentry files... success
🤖  Compiling sentry using --release flag...
In dev/sentry.cr:12:10

 12 | YAML.mapping(
           ^------
Warning: Deprecated YAML.mapping. use YAML::Serializable instead (the legacy behaviour is also available in a shard at github:crystal-lang/yaml_mapping.cr)

In dev/sentry.cr:12:5

 12 | YAML.mapping(
      ^
Warning: expanding macro

There was a problem expanding macro 'mapping'

Called macro defined in /usr/lib/crystal/yaml/mapping.cr:222:3

 222 | macro mapping(**_properties_)

Which expanded to:

 > 1 |     ::YAML.mapping({display_name: {type: ::Union(String, ::Nil), getter: false, setter: false, default: nil}, info: {type: Bool, default: false}, build: {type: ::Union(String, ::Nil), getter: false, default: nil}, build_args: {type: String, getter: false, default: ""}, run: {type: ::Union(String, ::Nil), getter: false, default: nil}, run_args: {type: String, getter: false, default: ""}, watch: {type: Array(String), default: ["./src/**/*.cr", "./src/**/*.ecr"]}, install_shards: {type: Bool, default: false}, colorize: {type: Bool, default: true}})
   2 |   
Warning: Deprecated YAML.mapping. use YAML::Serializable instead (the legacy behaviour is also available in a shard at github:crystal-lang/yaml_mapping.cr)

In dev/sentry.cr:215:23

 215 | app_process.kill
                   ^---
Warning: Deprecated Process#kill. Use #signal instead

In /usr/lib/crystal/process.cr:293:3

 293 | def kill(sig = Signal::TERM)
       ^---
Warning: Deprecated Process#kill. Use #signal instead

A total of 4 warnings were found.
🤖  Sentry installed!
`

> All the deprecated definitions will be removed for 1.0. We want a clean 1.0.
https://crystal-lang.org/2020/06/09/crystal-0.35.0-released.html

**Comment by samueleaton** [comment]
working on this now
